/**
 * 不适合作为文件夹图标的 Material Icons 名称集合
 * 这些图标具有明确的动作/导航/状态语义，不适合代表文件夹
 */
export const EXCLUDED_FOLDER_ICONS = new Set([
    // 动作类（明确的操作含义）
    'add',
    'add_circle',
    'add_circle_outline',
    'add_box',
    'create',
    'edit',
    'edit_note',
    'delete',
    'delete_forever',
    'remove',
    'remove_circle',
    'remove_circle_outline',
    'save',
    'save_as',
    'save_alt',
    'close',
    'done',
    'done_all',
    'check',
    'check_circle',
    'check_circle_outline',
    'clear',
    'cancel',
    'block',
    'dangerous',
    'refresh',
    'sync',
    'sync_alt',
    'search',
    'search_off',
    'manage_search',
    'send',
    'share',
    'reply',
    'forward',
    'upload',
    'upload_file',
    'download',
    'download_done',
    'print',
    'copy',
    'content_copy',
    'cut',
    'content_cut',
    'paste',
    'content_paste',
    'undo',
    'redo',
    'restore',
    'restore_from_trash',
    'backup',
    'launch',
    'open_in_new',
    'open_in_full',
    'open_with',
    'update',
    'upgrade',
    'start',
    'stop',
    'play_arrow',
    'pause',
    'skip_next',
    'skip_previous',
    // 导航类（方向/定位含义）
    'chevron_left',
    'chevron_right',
    'chevron_up',
    'chevron_down',
    'expand_less',
    'expand_more',
    'arrow_back',
    'arrow_forward',
    'arrow_upward',
    'arrow_downward',
    'arrow_back_ios',
    'arrow_forward_ios',
    'navigate_before',
    'navigate_next',
    'first_page',
    'last_page',
    'menu',
    'menu_open',
    'more_vert',
    'more_horiz',
    'home',
    'home_work',
    'subdirectory_arrow_left',
    'subdirectory_arrow_right',
    'unfold_more',
    'unfold_less',
    'swap_vert',
    'swap_horiz',
    // 状态/提示类（警告/状态含义）
    'error',
    'error_outline',
    'warning',
    'warning_amber',
    'info',
    'info_outline',
    'help',
    'help_outline',
    'question_mark',
    'notifications',
    'notifications_active',
    'notifications_off',
    'alarm',
    'alarm_on',
    'alarm_off',
    'report',
    'report_problem',
    'priority_high',
    'new_releases',
    'announcement',
    // 开关/选中类（交互状态含义）
    'toggle_on',
    'toggle_off',
    'toggle_off_outlined',
    'check_box',
    'check_box_outline_blank',
    'indeterminate_check_box',
    'radio_button_checked',
    'radio_button_unchecked',
    'star_border',
    'star_half',
    'grade',
    'stars',
    'favorite_border',
    // 输入/表单类
    'input',
    'input_circle',
    'radio',
    'radio_button_checked',
    'radio_button_unchecked',
    'switch_left',
    'switch_right',
    'drag_indicator',
    'drag_handle',
    'sort',
    'sort_by_alpha',
    'filter_list',
    'filter_alt',
    'settings',
    'settings_applications',
    'tune'
]);
/**
 * 虚拟目录可用图标候选列表（Material Icons 名称）
 * 用于创建新虚拟目录时自动分配唯一图标
 * 图标选择已通过 EXCLUDED_FOLDER_ICONS 过滤，确保只保留适合代表文件夹的图标
 */
export const FOLDER_ICONS = [
    'folder_special',
    'folder_open',
    'folder_shared',
    'collections_bookmark',
    'category',
    'topic',
    'library_books',
    'auto_stories',
    'dashboard',
    'account_tree',
    'collections',
    'video_library',
    'photo_library',
    'music_note',
    'article',
    'description',
    'movie',
    'science',
    'biotech',
    'palette',
    'explore',
    'travel_explore',
    'public',
    'language',
    'school',
    'menu_book',
    'book',
    'newspaper',
    'feed',
    'data_exploration',
    'query_stats',
    'insights',
    'analytics',
    'bubble_chart',
    'donut_large',
    'workspaces',
    'group_work',
    'psychology',
    'lightbulb',
    'tips_and_updates',
    'fact_check',
    'checklist',
    'integration_instructions',
    'star',
    'favorite',
    'history_edu',
    'diversity_3',
    // ─── 存储/容器类 ─────────────────────────────────────────────
    'inventory',
    'inventory_2',
    'archive',
    'all_inbox',
    'cloud',
    'cloud_queue',
    'bookmark',
    'bookmarks',
    'label',
    'rss_feed',
    'podcasts',
    'album',
    'library_music',
    'perm_media',
    // ─── 兴趣/主题类 ─────────────────────────────────────────────
    'interests',
    'widgets',
    'apps',
    'extension',
    'style',
    'layers',
    'auto_awesome',
    'eco',
    'forest',
    'park',
    'spa',
    'water_drop',
    'terrain',
    'landscape',
    'beach_access',
    'celebration',
    // ─── 创意/艺术类 ─────────────────────────────────────────────
    'brush',
    'draw',
    'colorize',
    'art_track',
    'theater_comedy',
    'local_activity',
    // ─── 游戏/娱乐类 ─────────────────────────────────────────────
    'sports_esports',
    'videogame_asset',
    'casino',
    'chess',
    'gamepad',
    'sports',
    'sports_soccer',
    'sports_basketball',
    'sports_tennis',
    // ─── 餐饮/生活类 ─────────────────────────────────────────────
    'restaurant',
    'restaurant_menu',
    'coffee',
    'local_cafe',
    'cake',
    'local_dining',
    'icecream',
    'set_meal',
    // ─── 旅行/地点类 ─────────────────────────────────────────────
    'flight',
    'map',
    'account_balance',
    'store',
    'storefront',
    'business',
    'work',
    'work_history',
    'apartment',
    'house',
    'cabin',
    'cottage',
    'villa',
    'real_estate_agent',
    // ─── 科技/自然类 ─────────────────────────────────────────────
    'rocket',
    'astronomy',
    'compost',
    'nature',
    'garden',
    'sunny',
    'rainy',
    'cloudy_snowing',
    'thunderstorm',
    // ─── 教育/知识类 ─────────────────────────────────────────────
    'dictionary',
    'translate',
    'local_library',
    'castle',
    'fort',
    'museum',
    'architecture',
    // ─── 音乐/媒体类 ─────────────────────────────────────────────
    'headphones',
    'mic',
    'radio',
    'surround_sound',
    'graphic_eq',
    'live_tv',
    'movie_creation',
    'movie_filter',
    'photo_camera',
    'videocam'
];
export class IconManager {
    db;
    constructor(db) {
        this.db = db;
    }
    /**
     * 获取所有已被使用的图标名称集合
     */
    getUsedIcons() {
        const rows = this.db
            .prepare('SELECT DISTINCT icon FROM virtual_directories WHERE icon IS NOT NULL AND icon != ?')
            .all('');
        return rows.map(r => r.icon);
    }
    /**
     * 挑选一个尚未被使用的唯一图标名称
     * @param candidates 候选图标名称列表
     * @returns 选中的图标名称，如果全部使用则返回第一个候选
     */
    pickUniqueIcon(candidates) {
        if (candidates.length === 0)
            return 'folder';
        const used = new Set(this.getUsedIcons());
        for (const icon of candidates) {
            if (!used.has(icon))
                return icon;
        }
        return candidates[0];
    }
}
//# sourceMappingURL=IconManager.js.map